apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest
  template:
    metadata:
      labels:
        app: nest
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: nest
        image: acrtallersoabel.azurecr.io/nest:1.2
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: '0'
            memory: '0'
          limits:
            cpu: '256'
            memory: 11400G
        env:
        - name: DB_USER
          value: "admin-app-1"
        - name: DB_PASSWORD
          value: "Agosto2024_"
        - name: DB_SERVER
          value: "app-1-server-db.database.windows.net"
        - name: DB_DATABASE
          value: "app-1-products"
        - name: DB_ENCRYPT
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: nest
spec:
  type: LoadBalancer
  ports:
    - targetPort: 3000
      name: port3000
      port: 3000
      protocol: TCP
  selector:
    app: nest
